apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-backend-cassandra
  name: myapp-backend-cassandra-ext
spec:
  type: LoadBalancer
  ports:
    - port: 9042
  selector:
    app: myapp-backend-cassandra